### ISSUE TITLE
This repository is empty.

### ISSUE THREAD

**Issue by fijixfiji** [akinomaeni/read-or-run#1]
This repository is empty.
なにかソースコードおいてください。

**Comment by akinomaeni** [comment]
@fijixfiji そうですね :smiley: 
Read or Run といえば何がいいでしょう？

**Comment by fijixfiji** [comment]
@akinomaeni 
はろーわーるど的に

``` python
print("read or run")
```

とか

``` ruby
print "read or run"
```

とか？:sunny:

**Comment by akinomaeni** [comment]
@fijixfiji Pythonですか？
Collaboratorsに追加したんでPushできるようになってるんでPushしてみて大丈夫ですよ！

**Comment by akinomaeni** [comment]
@fijixfiji Thx to initialize this repository :+1: 
I added hello.py in 054abd033bf9b9f87b62f6a26c9f83d7a7cf3971.

**Comment by fijixfiji** [comment]
1つ目はPythonで、2つ目がRubyな気がしてた。

**Comment by akinomaeni** [comment]
どっちもどっちもいけるね。Pythonだと改行が入ってRubyだと入らないのが違うのか。
